import React, { useEffect, useMemo, useState } from "react";
import { Canvas, useThree } from "@react-three/fiber";
import * as THREE from "three";
const DEFAULT_BUILDING={id:"B4",x:1.4,z:-.8,w:1.5,d:1.6,h:5.3,type:"commercial"};
const META={residential:{label:"Residential",wall:"#8eaaa5",accent:"#48e6ad",glass:"#b9e9df"},commercial:{label:"Commercial",wall:"#a17f4a",accent:"#efb44e",glass:"#dce9e8"},mixed:{label:"Mixed Use",wall:"#789ba0",accent:"#48cce9",glass:"#c7eff0"},agricultural:{label:"Agricultural",wall:"#75956b",accent:"#91c84c",glass:"#d3ead9"}};
function makeFloors(b){const n=Math.max(1,Math.min(6,Math.round(b?.h||5)));const arr=[{floor:"GF",unit:"Ground",use:b?.type==="agricultural"?"Farm / access":"Commercial",detail:"Retail, lobby, services and public-facing space",area:"1,420 sq.ft"}];for(let i=1;i<n;i++)arr.push({floor:`${i}F`,unit:`Unit ${i}01`,use:b?.type==="commercial"?"Office":"Residential",detail:i===n-1?"Top-floor unit with terrace access":"Typical upper-floor property unit",area:i===n-1?"1,240 sq.ft":"1,180 sq.ft"});return arr.reverse();}
function Win({x,y,z,side=false,lit=false}){return <mesh position={[x,y,z]} rotation={[0,side ? Math.PI/2 : 0,0]}><boxGeometry args={[side ? .055 : .62,.46,side ? .62 : .055]}/><meshStandardMaterial color={lit?"#fff0bf":"#9ed9d5"} emissive={lit?"#e5a84d":"#164345"} emissiveIntensity={lit?.65:.22} roughness={.18} metalness={.3}/></mesh>}
function Balcony({y,width,depth,accent}){return <group position={[0,y,depth/2+.36]}><mesh castShadow><boxGeometry args={[width,.10,.72]}/><meshStandardMaterial color="#d7dfdd" roughness={.55} metalness={.2}/></mesh>{[-.45,-.22,0,.22,.45].map((x,i)=><mesh key={i} position={[x*width/2,.28,.3]}><cylinderGeometry args={[.014,.014,.54,8]}/><meshStandardMaterial color="#b7d8d2"/></mesh>)}<mesh position={[0,.55,.3]}><boxGeometry args={[width,.025,.025]}/><meshBasicMaterial color={accent}/></mesh></group>}
function Tree({x,z,s=1}){return <group position={[x,0,z]} scale={s}><mesh position={[0,.38,0]}><cylinderGeometry args={[.05,.07,.65,8]}/><meshStandardMaterial color="#654d34"/></mesh><mesh position={[0,.83,0]}><sphereGeometry args={[.32,12,10]}/><meshStandardMaterial color="#2f7c5b"/></mesh></group>}
function Car({x,z,rot=0}){return <group position={[x,.08,z]} rotation={[0,rot,0]}><mesh castShadow><boxGeometry args={[.9,.18,.45]}/><meshStandardMaterial color="#9ca9aa" metalness={.55} roughness={.25}/></mesh><mesh position={[0,.12,0]}><boxGeometry args={[.45,.12,.34]}/><meshStandardMaterial color="#18272b" roughness={.15}/></mesh><mesh position={[-.3,-.13,-.18]}><cylinderGeometry args={[.07,.07,.05,12]} rotation={[Math.PI/2,0,0]}/><meshStandardMaterial color="#101516"/></mesh><mesh position={[.3,-.13,.18]}><cylinderGeometry args={[.07,.07,.05,12]} rotation={[Math.PI/2,0,0]}/><meshStandardMaterial color="#101516"/></mesh></group>}
function BuildingScene({building,floors,active,setActive,viewMode,night}){const {camera}=useThree();const total=floors.length;const p=META[building?.type]||META.mixed;const width=(building?.w||1.5)*3.0;const depth=(building?.d||1.6)*2.25;const fh=.92;const base=.55;const top=base+(total-1)*fh+.9;
 useEffect(()=>{const pos=viewMode==="aerial"?[10,12,12]:viewMode==="side"?[11,5.4,2]:[8.8,6.7,10.5];camera.position.set(...pos);camera.lookAt(0,top*.46,0)},[camera,viewMode,top,building?.id]);
 return <><color attach="background" args={[night?"#01060a":"#06151a"]}/><ambientLight intensity={night?.62:1.2}/><directionalLight castShadow position={[7,14,9]} intensity={night?1.6:4.2} color={night?"#7fa6c4":"#effff9"}/><pointLight position={[-6,4,-5]} intensity={night?30:15} distance={18} color="#39e3ae"/><pointLight position={[5,5,6]} intensity={night?24:10} distance={15} color="#42c9ef"/>
 <mesh rotation-x={-Math.PI/2} position={[0,-.25,0]} receiveShadow><planeGeometry args={[18,14]}/><meshStandardMaterial color={night?"#061016":"#0b1d21"} roughness={.95}/></mesh>
 <mesh rotation-x={-Math.PI/2} position={[0,-.19,0]}><planeGeometry args={[width+2.6,depth+2.8]}/><meshStandardMaterial color="#173334" roughness={.88}/></mesh>
 <mesh rotation-x={-Math.PI/2} position={[0,-.15,depth/2+3.9]}><planeGeometry args={[18,1.35]}/><meshStandardMaterial color="#171e20"/></mesh>
 <mesh rotation-x={-Math.PI/2} position={[-6,-.15,0]}><planeGeometry args={[1.1,10]}/><meshStandardMaterial color="#171e20"/></mesh>
 <mesh position={[0,-.02,0]} receiveShadow><boxGeometry args={[width+.7,.24,depth+.7]}/><meshStandardMaterial color="#24484a" roughness={.78}/></mesh>
 {floors.map((f,i)=>{const actualIndex=total-1-i;const y=base+actualIndex*fh;const activeNow=i===active;return <group key={f.floor} position={[0,y,0]} onClick={e=>{e.stopPropagation();setActive(i)}}>
   <mesh castShadow receiveShadow><boxGeometry args={[width,.78,depth]}/><meshStandardMaterial color={activeNow?"#a6ead8":p.wall} emissive={activeNow?p.accent:"#071e20"} emissiveIntensity={activeNow?.2:.04} roughness={.55} metalness={.12}/></mesh>
   <mesh position={[0,.42,0]}><boxGeometry args={[width+.06,.07,depth+.06]}/><meshStandardMaterial color="#24393a" roughness={.7}/></mesh>
   {[[-.34,0,.34],[-.34,0,.34]].map((_,sideIndex)=>null)}
   {[-.38,0,.38].map((r,j)=><Win key={`f${j}`} x={r*width} y={0} z={depth/2+.032} lit={activeNow&&j===1}/>) }
   {[-.35,0,.35].map((r,j)=><Win key={`s${j}`} x={width/2+.032} y={0} z={r*depth} side lit={activeNow&&j===0}/>) }
   {!i&&<Balcony y={.02} width={Math.min(width*.6,4.2)} depth={depth} accent={p.accent}/>} 
 </group>})}
 <mesh position={[0,top+.1,0]} castShadow><boxGeometry args={[width+.1,.14,depth+.1]}/><meshStandardMaterial color="#263f40"/></mesh>
 <mesh position={[0,top+.38,0]}><boxGeometry args={[width*.45,.36,depth*.32]}/><meshStandardMaterial color="#314f50"/></mesh>
 {Array.from({length:6}).map((_,i)=><mesh key={i} position={[-width*.25+i*width*.1,top+.47,0]} rotation={[-.55,0,0]}><boxGeometry args={[.34,.025,.5]}/><meshStandardMaterial color="#243f46" metalness={.6}/></mesh>)}
 <mesh position={[0,top+.8,0]}><cylinderGeometry args={[.025,.025,1,10]}/><meshStandardMaterial color="#78eac5" emissive="#37dba9" emissiveIntensity={.5}/></mesh>
 <Tree x={-width/2-1.2} z={depth/2+1.2}/><Tree x={width/2+1.1} z={depth/2+1.1} s={.85}/><Tree x={-width/2-1.1} z={-depth/2-1.1} s={.8}/><Car x={width/2+1.8} z={depth/2+3.2} rot={Math.PI/2}/><Car x={-width/2-1.7} z={depth/2+3.2} rot={Math.PI/2}/>
 </>}
export default function PropertyTwin({compact=false,selectedBuilding=DEFAULT_BUILDING}){const building=selectedBuilding||DEFAULT_BUILDING;const floors=useMemo(()=>makeFloors(building),[building]);const [active,setActive]=useState(0);const [viewMode,setViewMode]=useState("front");const [night,setNight]=useState(false);useEffect(()=>setActive(0),[building?.id]);const f=floors[active]||floors[0];const meta=META[building.type]||META.mixed;const ulpin=`TG-HYD-${String(building.id||"B4").padStart(2,"0")}-2026-0045`;return <div className={`property-twin-v4 ${compact?"compact":""}`}>
 <div className="twin-canvas-v4"><Canvas shadows dpr={[1,1.8]} camera={{position:[8.8,6.7,10.5],fov:38,near:.1,far:100}}><BuildingScene building={building} floors={floors} active={active} setActive={setActive} viewMode={viewMode} night={night}/></Canvas>
   <div className="twin-breadcrumb">3D DIGITAL TWIN <span>›</span> Hyderabad <span>›</span> <b>City Block {building.id}</b></div>
   <div className="twin-view-controls"><button className={viewMode==="front"?"active":""} onClick={()=>setViewMode("front")}>Realistic</button><button className={viewMode==="side"?"active":""} onClick={()=>setViewMode("side")}>Side</button><button className={viewMode==="aerial"?"active":""} onClick={()=>setViewMode("aerial")}>Aerial</button><button className={night?"active":""} onClick={()=>setNight(v=>!v)}>{night?"Night":"Day"}</button></div>
   <div className="twin-help">Drag to rotate · Scroll to zoom · Click a floor to inspect</div>
 </div>
 <aside className="twin-details-v4"><div className="mini-label">PROPERTY DIGITAL TWIN <span className="verified-pill">✓ VERIFIED</span></div><h3>{f.floor} · {f.unit}</h3><p>{f.detail} · {f.area}</p><div className="twin-selected-id"><span>SELECTED FROM EXPLORE MAP</span><b>City Block {building.id}</b><small>{meta.label} · {floors.length-1}F + Ground</small></div>
 <div className="twin-floor-list">{floors.map((x,i)=><button key={x.floor} className={i===active?"active":""} onClick={()=>setActive(i)}><span>{x.floor}</span><div><b>{x.unit}</b><small>{x.use}</small></div><em>›</em></button>)}</div>
 <div className="property-facts"><div><small>ULPIN</small><b>{ulpin}</b></div><div><small>LOCATION</small><b>Gachibowli, Hyderabad, Telangana</b></div><div><small>PARCEL AREA</small><b>{Math.round((building.w||1.5)*(building.d||1.6)*1450).toLocaleString()} sq.m</b></div><div><small>BUILT-UP AREA</small><b>{Math.round((building.w||1.5)*(building.d||1.6)*520).toLocaleString()} sq.m</b></div><div><small>STATUS</small><b className="ok">Verified demo record</b></div></div>
 <button className="primary-v4 full report-btn" onClick={()=>alert(`Property report for City Block ${building.id} — prototype demo.`)}>View Full Property Report →</button>
 </aside>
 </div>}
